### ISSUE TITLE
Apple pay is not working

### ISSUE THREAD

**Issue by ramisalem** [network-international/react-native-ngenius#8]
Hello,  I checked the code of this package and I find out that the initiateApplePay method has two parameters first is applePayConfig which is an object, and the second is the order, where it has been written wrong in the docs 

After I edited the code I am getting 
 ``` 
const applePayConfig = {
      merchantIdentifier: '*****',
      countryCode: 'UAE',
      totalAmount: total,
      currencyCode: 'AED',
      merchantName: '*****',
    };
    try {
      const resp = await initiateApplePay(o, applePayConfig);
    } catch (err) {
      console.log({ err });
    } 
 
result "err": {"error": undefined, "status": "Failed"}}  
````

Could you please tell me what did I  miss?

**Comment by mu1ex** [comment]
Thank you, we have updated the readme. Also have you enabled apple pay in the merchant portal?

**Comment by kareem-ali-abdelsalam** [comment]
@mu1ex We have this version 1.1.1 already, did you try it ?

**Comment by mu1ex** [comment]
Yes @kareem-ali-abdelsalam, it works. If the payment is declined, it's got to do with the certificate mismatch. I would recommend you to create a new MID in Apple's dev portal, configure the same in NGenius Portal, by downloading and uploading the CSR and signed certificates respectively against the new MID.

**Comment by kareem-ali-abdelsalam** [comment]
Thank you @mu1ex, How can i configure it on NGenius Portal ?

**Comment by iKambad3618** [comment]
@mu1ex 
I installed "@network-international/react-native-ngenius": "^1.1.3", iOS Supported version is 11.0
also all setup done in NGenius Portal, but still getting
{"error": undefined, "status": "Failed"}

it's got to do with the certificate mismatch.
My certificate is also valid and also created new once and uploaded on NGenius Portal

**Comment by mu1ex** [comment]
@iKambad3618 , the certificate mismatch will require you to change the Apple MID and reconfigure the certs on the App and NGenius portal.

**Comment by wang-yazhou** [comment]
@iKambad3618 @ramisalem 

Have you solved this problem？
